blueprint:
  domain: automation
  name: "Sports: Start Monitor"
  description: 'This blueprint announces the start of a game at 60, 30, and 10-minute marks, flashes team colors, and plays an MP3.'
  input:
    teams:
      name: Teams
      description: Teams whose games you want to monitor.
      selector:
        entity:
          integration: teamtracker
          multiple: true
    light_targets:
      name: Lights to flash
      description: Choose one or more lights.
      selector:
        entity:
          domain: light
          multiple: true
    repeat_count:
      name: Repeat count
      description: How many times should the color cycle run?
      selector:
        number:
          min: 1
          max: 15
          mode: slider
          step: 1
      default: 3
    media_player_target:
      name: Media Player
      description: Select the media player to play the sound.
      selector:
        entity:
          domain: media_player
    media_content:
      name: Media Content ID
      description: The content ID for the sound to play.
      selector:
        text:
    volume_level:
      name: Volume Level
      description: Set the volume level for the media player.
      selector:
        number:
          min: 0.1
          max: 1.0
          mode: slider
          step: 0.1
      default: 0.8

trigger:
  - platform: state
    entity_id: !input teams
    to: 'IN'

action:
  - choose:
      - conditions: "{{ trigger.to_state.state == 'IN' }}"
        sequence:
          - service: media_player.volume_set
            data:
              entity_id: !input media_player_target
              volume_level: !input volume_level
          - service: media_player.play_media
            data:
              entity_id: !input media_player_target
              media_content_id: !input media_content
              media_content_type: music
          - service: scene.create
            data:
              snapshot_entities: !input light_targets
              scene_id: team_game_start_lights_capture
          - repeat:
              count: !input repeat_count
              sequence:
                - service: light.turn_on
                  data_template:
                    entity_id: "{{ light_entity }}"
                    rgb_color: >
                      {% set color_str = state_attr(trigger.entity_id, 'team_colors')[0] %}
                      {{ [color_str[1:3] | int(base=16), color_str[3:5] | int(base=16), color_str[5:7] | int(base=16)] if color_str else [255, 255, 255] }}
                - delay:
                    seconds: 1.5
                - service: light.turn_on
                  data_template:
                    entity_id: "{{ light_entity }}"
                    rgb_color: >
                      {% set color_str = state_attr(trigger.entity_id, 'team_colors')[1] %}
                      {{ [color_str[1:3] | int(base=16), color_str[3:5] | int(base=16), color_str[5:7] | int(base=16)] if color_str else [255, 255, 255] }}
                - delay:
                    seconds: 1.5
          - service: scene.turn_on
            data:
              entity_id: scene.team_game_start_lights_capture

variables:
  light_entity: !input light_targets
